// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWho3T0BRcLA345S0G3iGLmX0_egnwfdc',
    appId: '1:970290217543:web:b8ee9518f24f917c172762',
    messagingSenderId: '970290217543',
    projectId: 'ht-ai-21eea',
    authDomain: 'ht-ai-21eea.firebaseapp.com',
    storageBucket: 'ht-ai-21eea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbwfaeFPnsmCamCQ5eY7vlOIWhaCVmwco',
    appId: '1:970290217543:android:97199b8f59286e6d172762',
    messagingSenderId: '970290217543',
    projectId: 'ht-ai-21eea',
    storageBucket: 'ht-ai-21eea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6RC3hYI34C9U60GCY6H_8lSBZZrQ-7IM',
    appId: '1:970290217543:ios:b297002eea00dab2172762',
    messagingSenderId: '970290217543',
    projectId: 'ht-ai-21eea',
    storageBucket: 'ht-ai-21eea.appspot.com',
    iosBundleId: 'com.sadick.healthTrackAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6RC3hYI34C9U60GCY6H_8lSBZZrQ-7IM',
    appId: '1:970290217543:ios:b297002eea00dab2172762',
    messagingSenderId: '970290217543',
    projectId: 'ht-ai-21eea',
    storageBucket: 'ht-ai-21eea.appspot.com',
    iosBundleId: 'com.sadick.healthTrackAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWho3T0BRcLA345S0G3iGLmX0_egnwfdc',
    appId: '1:970290217543:web:a0e730ea2e9b593d172762',
    messagingSenderId: '970290217543',
    projectId: 'ht-ai-21eea',
    authDomain: 'ht-ai-21eea.firebaseapp.com',
    storageBucket: 'ht-ai-21eea.appspot.com',
  );
}
